language: python

python:
  - "3.8"


# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run code checker & tests
script:
  - pylint --exit-zero manifestapp
  - coverage run -m unittest tests
  - coverage report

after_success:
  - coveralls