language: python

python:
  - "3.9"      # current default Python on Travis CI


# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls


# command to run code checker & tests
script:
  - pylint --exit-zero manifestapp
#  - unittest

after_success:
  - coveralls