"""empty message

Revision ID: 23367ef6e1cf
Revises: 41661dafa444
Create Date: 2023-03-08 17:18:13.670968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23367ef6e1cf'
down_revision = '41661dafa444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('pwd_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('pwd_hash',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
