"""empty message

Revision ID: 90676c73ed6f
Revises: 23367ef6e1cf
Create Date: 2023-03-08 17:25:10.928146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90676c73ed6f'
down_revision = '23367ef6e1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('pwd_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('pwd_hash',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
