"""empty message

Revision ID: b7220b384ffe
Revises: 
Create Date: 2023-02-15 22:41:04.495799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7220b384ffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=45), nullable=False),
    sa.Column('lname', sa.String(length=45), nullable=False),
    sa.Column('seatno', sa.String(length=3), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('comments', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('passengerID', sa.Integer(), nullable=False),
    sa.Column('geo_location', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=90), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('other_pass', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['passengerID'], ['passengers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('passengers')
    # ### end Alembic commands ###
